// Package broker provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package broker

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	ApiKeyAuthScopes = "ApiKeyAuth.Scopes"
)

// Defines values for ProviderProfileAuthHeader.
const (
	ClientSecretBasic ProviderProfileAuthHeader = "client_secret_basic"
	ClientSecretPost  ProviderProfileAuthHeader = "client_secret_post"
)

// Defines values for ProviderProfileAuthType.
const (
	ApiKey    ProviderProfileAuthType = "api_key"
	BasicAuth ProviderProfileAuthType = "basic_auth"
	Oauth2    ProviderProfileAuthType = "oauth2"
)

// ConsentSpecRequest defines model for ConsentSpecRequest.
type ConsentSpecRequest struct {
	ProviderId  *string   `json:"provider_id,omitempty"`
	ReturnUrl   string    `json:"return_url"`
	Scopes      *[]string `json:"scopes,omitempty"`
	WorkspaceId string    `json:"workspace_id"`
}

// ConsentSpecResponse defines model for ConsentSpecResponse.
type ConsentSpecResponse struct {
	AuthUrl    *string   `json:"authUrl,omitempty"`
	ProviderId *string   `json:"provider_id,omitempty"`
	Scopes     *[]string `json:"scopes,omitempty"`
	State      *string   `json:"state,omitempty"`
}

// MetadataResponse Grouped provider metadata
type MetadataResponse map[string]map[string]struct {
	ApiBaseUrl       *string   `json:"api_base_url,omitempty"`
	Scopes           *[]string `json:"scopes,omitempty"`
	UserInfoEndpoint *string   `json:"user_info_endpoint,omitempty"`
}

// ProviderProfile defines model for ProviderProfile.
type ProviderProfile struct {
	// ApiBaseUrl Root URL for the provider's API (e.g., https://api.github.com)
	ApiBaseUrl *string `json:"api_base_url,omitempty"`

	// AuthHeader Method for sending client secret during token exchange.
	AuthHeader   *ProviderProfileAuthHeader `json:"auth_header,omitempty"`
	AuthType     *ProviderProfileAuthType   `json:"auth_type,omitempty"`
	AuthUrl      *string                    `json:"auth_url,omitempty"`
	ClientId     *string                    `json:"client_id,omitempty"`
	ClientSecret *string                    `json:"client_secret,omitempty"`
	Id           *openapi_types.UUID        `json:"id,omitempty"`

	// Name Unique slug for the provider (e.g. "google", "github")
	Name string `json:"name"`

	// Params Provider-specific extra parameters (e.g., prompt, access_type)
	Params   *map[string]interface{} `json:"params,omitempty"`
	Scopes   *[]string               `json:"scopes,omitempty"`
	TokenUrl *string                 `json:"token_url,omitempty"`

	// UserInfoEndpoint Path to fetch user info (e.g., /user)
	UserInfoEndpoint *string `json:"user_info_endpoint,omitempty"`
}

// ProviderProfileAuthHeader Method for sending client secret during token exchange.
type ProviderProfileAuthHeader string

// ProviderProfileAuthType defines model for ProviderProfile.AuthType.
type ProviderProfileAuthType string

// TokenResponse defines model for TokenResponse.
type TokenResponse struct {
	AccessToken  *string    `json:"access_token,omitempty"`
	Expiry       *time.Time `json:"expiry,omitempty"`
	IdToken      *string    `json:"id_token,omitempty"`
	RefreshToken *string    `json:"refresh_token,omitempty"`
	TokenType    *string    `json:"token_type,omitempty"`
}

// GetAuthCallbackParams defines parameters for GetAuthCallback.
type GetAuthCallbackParams struct {
	Code  *string `form:"code,omitempty" json:"code,omitempty"`
	State *string `form:"state,omitempty" json:"state,omitempty"`
}

// PostProvidersJSONBody defines parameters for PostProviders.
type PostProvidersJSONBody struct {
	Profile *ProviderProfile `json:"profile,omitempty"`
}

// PostAuthConsentSpecJSONRequestBody defines body for PostAuthConsentSpec for application/json ContentType.
type PostAuthConsentSpecJSONRequestBody = ConsentSpecRequest

// PostProvidersJSONRequestBody defines body for PostProviders for application/json ContentType.
type PostProvidersJSONRequestBody PostProvidersJSONBody

// PutProvidersIdJSONRequestBody defines body for PutProvidersId for application/json ContentType.
type PutProvidersIdJSONRequestBody = ProviderProfile

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetAuthCallback request
	GetAuthCallback(ctx context.Context, params *GetAuthCallbackParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostAuthConsentSpecWithBody request with any body
	PostAuthConsentSpecWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostAuthConsentSpec(ctx context.Context, body PostAuthConsentSpecJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostConnectionsConnectionIDRefresh request
	PostConnectionsConnectionIDRefresh(ctx context.Context, connectionID string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetConnectionsConnectionIDToken request
	GetConnectionsConnectionIDToken(ctx context.Context, connectionID string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetHealth request
	GetHealth(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetProviders request
	GetProviders(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostProvidersWithBody request with any body
	PostProvidersWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostProviders(ctx context.Context, body PostProvidersJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetProvidersByNameName request
	GetProvidersByNameName(ctx context.Context, name string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetProvidersMetadata request
	GetProvidersMetadata(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteProvidersId request
	DeleteProvidersId(ctx context.Context, id openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetProvidersId request
	GetProvidersId(ctx context.Context, id openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PutProvidersIdWithBody request with any body
	PutProvidersIdWithBody(ctx context.Context, id openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PutProvidersId(ctx context.Context, id openapi_types.UUID, body PutProvidersIdJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetAuthCallback(ctx context.Context, params *GetAuthCallbackParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetAuthCallbackRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostAuthConsentSpecWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostAuthConsentSpecRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostAuthConsentSpec(ctx context.Context, body PostAuthConsentSpecJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostAuthConsentSpecRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostConnectionsConnectionIDRefresh(ctx context.Context, connectionID string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostConnectionsConnectionIDRefreshRequest(c.Server, connectionID)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetConnectionsConnectionIDToken(ctx context.Context, connectionID string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetConnectionsConnectionIDTokenRequest(c.Server, connectionID)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetHealth(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetHealthRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetProviders(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetProvidersRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostProvidersWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostProvidersRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostProviders(ctx context.Context, body PostProvidersJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostProvidersRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetProvidersByNameName(ctx context.Context, name string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetProvidersByNameNameRequest(c.Server, name)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetProvidersMetadata(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetProvidersMetadataRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteProvidersId(ctx context.Context, id openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteProvidersIdRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetProvidersId(ctx context.Context, id openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetProvidersIdRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PutProvidersIdWithBody(ctx context.Context, id openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutProvidersIdRequestWithBody(c.Server, id, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PutProvidersId(ctx context.Context, id openapi_types.UUID, body PutProvidersIdJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutProvidersIdRequest(c.Server, id, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetAuthCallbackRequest generates requests for GetAuthCallback
func NewGetAuthCallbackRequest(server string, params *GetAuthCallbackParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/auth/callback")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Code != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "code", runtime.ParamLocationQuery, *params.Code); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.State != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "state", runtime.ParamLocationQuery, *params.State); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostAuthConsentSpecRequest calls the generic PostAuthConsentSpec builder with application/json body
func NewPostAuthConsentSpecRequest(server string, body PostAuthConsentSpecJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostAuthConsentSpecRequestWithBody(server, "application/json", bodyReader)
}

// NewPostAuthConsentSpecRequestWithBody generates requests for PostAuthConsentSpec with any type of body
func NewPostAuthConsentSpecRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/auth/consent-spec")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPostConnectionsConnectionIDRefreshRequest generates requests for PostConnectionsConnectionIDRefresh
func NewPostConnectionsConnectionIDRefreshRequest(server string, connectionID string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "connectionID", runtime.ParamLocationPath, connectionID)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/connections/%s/refresh", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetConnectionsConnectionIDTokenRequest generates requests for GetConnectionsConnectionIDToken
func NewGetConnectionsConnectionIDTokenRequest(server string, connectionID string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "connectionID", runtime.ParamLocationPath, connectionID)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/connections/%s/token", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetHealthRequest generates requests for GetHealth
func NewGetHealthRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/health")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetProvidersRequest generates requests for GetProviders
func NewGetProvidersRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/providers")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostProvidersRequest calls the generic PostProviders builder with application/json body
func NewPostProvidersRequest(server string, body PostProvidersJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostProvidersRequestWithBody(server, "application/json", bodyReader)
}

// NewPostProvidersRequestWithBody generates requests for PostProviders with any type of body
func NewPostProvidersRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/providers")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetProvidersByNameNameRequest generates requests for GetProvidersByNameName
func NewGetProvidersByNameNameRequest(server string, name string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "name", runtime.ParamLocationPath, name)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/providers/by-name/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetProvidersMetadataRequest generates requests for GetProvidersMetadata
func NewGetProvidersMetadataRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/providers/metadata")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewDeleteProvidersIdRequest generates requests for DeleteProvidersId
func NewDeleteProvidersIdRequest(server string, id openapi_types.UUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/providers/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetProvidersIdRequest generates requests for GetProvidersId
func NewGetProvidersIdRequest(server string, id openapi_types.UUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/providers/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPutProvidersIdRequest calls the generic PutProvidersId builder with application/json body
func NewPutProvidersIdRequest(server string, id openapi_types.UUID, body PutProvidersIdJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPutProvidersIdRequestWithBody(server, id, "application/json", bodyReader)
}

// NewPutProvidersIdRequestWithBody generates requests for PutProvidersId with any type of body
func NewPutProvidersIdRequestWithBody(server string, id openapi_types.UUID, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/providers/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetAuthCallbackWithResponse request
	GetAuthCallbackWithResponse(ctx context.Context, params *GetAuthCallbackParams, reqEditors ...RequestEditorFn) (*GetAuthCallbackResponse, error)

	// PostAuthConsentSpecWithBodyWithResponse request with any body
	PostAuthConsentSpecWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostAuthConsentSpecResponse, error)

	PostAuthConsentSpecWithResponse(ctx context.Context, body PostAuthConsentSpecJSONRequestBody, reqEditors ...RequestEditorFn) (*PostAuthConsentSpecResponse, error)

	// PostConnectionsConnectionIDRefreshWithResponse request
	PostConnectionsConnectionIDRefreshWithResponse(ctx context.Context, connectionID string, reqEditors ...RequestEditorFn) (*PostConnectionsConnectionIDRefreshResponse, error)

	// GetConnectionsConnectionIDTokenWithResponse request
	GetConnectionsConnectionIDTokenWithResponse(ctx context.Context, connectionID string, reqEditors ...RequestEditorFn) (*GetConnectionsConnectionIDTokenResponse, error)

	// GetHealthWithResponse request
	GetHealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHealthResponse, error)

	// GetProvidersWithResponse request
	GetProvidersWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetProvidersResponse, error)

	// PostProvidersWithBodyWithResponse request with any body
	PostProvidersWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostProvidersResponse, error)

	PostProvidersWithResponse(ctx context.Context, body PostProvidersJSONRequestBody, reqEditors ...RequestEditorFn) (*PostProvidersResponse, error)

	// GetProvidersByNameNameWithResponse request
	GetProvidersByNameNameWithResponse(ctx context.Context, name string, reqEditors ...RequestEditorFn) (*GetProvidersByNameNameResponse, error)

	// GetProvidersMetadataWithResponse request
	GetProvidersMetadataWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetProvidersMetadataResponse, error)

	// DeleteProvidersIdWithResponse request
	DeleteProvidersIdWithResponse(ctx context.Context, id openapi_types.UUID, reqEditors ...RequestEditorFn) (*DeleteProvidersIdResponse, error)

	// GetProvidersIdWithResponse request
	GetProvidersIdWithResponse(ctx context.Context, id openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetProvidersIdResponse, error)

	// PutProvidersIdWithBodyWithResponse request with any body
	PutProvidersIdWithBodyWithResponse(ctx context.Context, id openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutProvidersIdResponse, error)

	PutProvidersIdWithResponse(ctx context.Context, id openapi_types.UUID, body PutProvidersIdJSONRequestBody, reqEditors ...RequestEditorFn) (*PutProvidersIdResponse, error)
}

type GetAuthCallbackResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r GetAuthCallbackResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetAuthCallbackResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostAuthConsentSpecResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ConsentSpecResponse
}

// Status returns HTTPResponse.Status
func (r PostAuthConsentSpecResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostAuthConsentSpecResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostConnectionsConnectionIDRefreshResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *TokenResponse
}

// Status returns HTTPResponse.Status
func (r PostConnectionsConnectionIDRefreshResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostConnectionsConnectionIDRefreshResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetConnectionsConnectionIDTokenResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *TokenResponse
}

// Status returns HTTPResponse.Status
func (r GetConnectionsConnectionIDTokenResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetConnectionsConnectionIDTokenResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetHealthResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r GetHealthResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetHealthResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetProvidersResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]struct {
		Id   *string `json:"id,omitempty"`
		Name *string `json:"name,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r GetProvidersResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetProvidersResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostProvidersResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *struct {
		Id      *string `json:"id,omitempty"`
		Message *string `json:"message,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r PostProvidersResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostProvidersResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetProvidersByNameNameResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *struct {
		Id *string `json:"id,omitempty"`
	}
}

// Status returns HTTPResponse.Status
func (r GetProvidersByNameNameResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetProvidersByNameNameResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetProvidersMetadataResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *MetadataResponse
}

// Status returns HTTPResponse.Status
func (r GetProvidersMetadataResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetProvidersMetadataResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteProvidersIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r DeleteProvidersIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteProvidersIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetProvidersIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ProviderProfile
}

// Status returns HTTPResponse.Status
func (r GetProvidersIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetProvidersIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PutProvidersIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r PutProvidersIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PutProvidersIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetAuthCallbackWithResponse request returning *GetAuthCallbackResponse
func (c *ClientWithResponses) GetAuthCallbackWithResponse(ctx context.Context, params *GetAuthCallbackParams, reqEditors ...RequestEditorFn) (*GetAuthCallbackResponse, error) {
	rsp, err := c.GetAuthCallback(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetAuthCallbackResponse(rsp)
}

// PostAuthConsentSpecWithBodyWithResponse request with arbitrary body returning *PostAuthConsentSpecResponse
func (c *ClientWithResponses) PostAuthConsentSpecWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostAuthConsentSpecResponse, error) {
	rsp, err := c.PostAuthConsentSpecWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostAuthConsentSpecResponse(rsp)
}

func (c *ClientWithResponses) PostAuthConsentSpecWithResponse(ctx context.Context, body PostAuthConsentSpecJSONRequestBody, reqEditors ...RequestEditorFn) (*PostAuthConsentSpecResponse, error) {
	rsp, err := c.PostAuthConsentSpec(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostAuthConsentSpecResponse(rsp)
}

// PostConnectionsConnectionIDRefreshWithResponse request returning *PostConnectionsConnectionIDRefreshResponse
func (c *ClientWithResponses) PostConnectionsConnectionIDRefreshWithResponse(ctx context.Context, connectionID string, reqEditors ...RequestEditorFn) (*PostConnectionsConnectionIDRefreshResponse, error) {
	rsp, err := c.PostConnectionsConnectionIDRefresh(ctx, connectionID, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostConnectionsConnectionIDRefreshResponse(rsp)
}

// GetConnectionsConnectionIDTokenWithResponse request returning *GetConnectionsConnectionIDTokenResponse
func (c *ClientWithResponses) GetConnectionsConnectionIDTokenWithResponse(ctx context.Context, connectionID string, reqEditors ...RequestEditorFn) (*GetConnectionsConnectionIDTokenResponse, error) {
	rsp, err := c.GetConnectionsConnectionIDToken(ctx, connectionID, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetConnectionsConnectionIDTokenResponse(rsp)
}

// GetHealthWithResponse request returning *GetHealthResponse
func (c *ClientWithResponses) GetHealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHealthResponse, error) {
	rsp, err := c.GetHealth(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetHealthResponse(rsp)
}

// GetProvidersWithResponse request returning *GetProvidersResponse
func (c *ClientWithResponses) GetProvidersWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetProvidersResponse, error) {
	rsp, err := c.GetProviders(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetProvidersResponse(rsp)
}

// PostProvidersWithBodyWithResponse request with arbitrary body returning *PostProvidersResponse
func (c *ClientWithResponses) PostProvidersWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostProvidersResponse, error) {
	rsp, err := c.PostProvidersWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostProvidersResponse(rsp)
}

func (c *ClientWithResponses) PostProvidersWithResponse(ctx context.Context, body PostProvidersJSONRequestBody, reqEditors ...RequestEditorFn) (*PostProvidersResponse, error) {
	rsp, err := c.PostProviders(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostProvidersResponse(rsp)
}

// GetProvidersByNameNameWithResponse request returning *GetProvidersByNameNameResponse
func (c *ClientWithResponses) GetProvidersByNameNameWithResponse(ctx context.Context, name string, reqEditors ...RequestEditorFn) (*GetProvidersByNameNameResponse, error) {
	rsp, err := c.GetProvidersByNameName(ctx, name, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetProvidersByNameNameResponse(rsp)
}

// GetProvidersMetadataWithResponse request returning *GetProvidersMetadataResponse
func (c *ClientWithResponses) GetProvidersMetadataWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetProvidersMetadataResponse, error) {
	rsp, err := c.GetProvidersMetadata(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetProvidersMetadataResponse(rsp)
}

// DeleteProvidersIdWithResponse request returning *DeleteProvidersIdResponse
func (c *ClientWithResponses) DeleteProvidersIdWithResponse(ctx context.Context, id openapi_types.UUID, reqEditors ...RequestEditorFn) (*DeleteProvidersIdResponse, error) {
	rsp, err := c.DeleteProvidersId(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteProvidersIdResponse(rsp)
}

// GetProvidersIdWithResponse request returning *GetProvidersIdResponse
func (c *ClientWithResponses) GetProvidersIdWithResponse(ctx context.Context, id openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetProvidersIdResponse, error) {
	rsp, err := c.GetProvidersId(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetProvidersIdResponse(rsp)
}

// PutProvidersIdWithBodyWithResponse request with arbitrary body returning *PutProvidersIdResponse
func (c *ClientWithResponses) PutProvidersIdWithBodyWithResponse(ctx context.Context, id openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutProvidersIdResponse, error) {
	rsp, err := c.PutProvidersIdWithBody(ctx, id, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutProvidersIdResponse(rsp)
}

func (c *ClientWithResponses) PutProvidersIdWithResponse(ctx context.Context, id openapi_types.UUID, body PutProvidersIdJSONRequestBody, reqEditors ...RequestEditorFn) (*PutProvidersIdResponse, error) {
	rsp, err := c.PutProvidersId(ctx, id, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutProvidersIdResponse(rsp)
}

// ParseGetAuthCallbackResponse parses an HTTP response from a GetAuthCallbackWithResponse call
func ParseGetAuthCallbackResponse(rsp *http.Response) (*GetAuthCallbackResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetAuthCallbackResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParsePostAuthConsentSpecResponse parses an HTTP response from a PostAuthConsentSpecWithResponse call
func ParsePostAuthConsentSpecResponse(rsp *http.Response) (*PostAuthConsentSpecResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostAuthConsentSpecResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ConsentSpecResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostConnectionsConnectionIDRefreshResponse parses an HTTP response from a PostConnectionsConnectionIDRefreshWithResponse call
func ParsePostConnectionsConnectionIDRefreshResponse(rsp *http.Response) (*PostConnectionsConnectionIDRefreshResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostConnectionsConnectionIDRefreshResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest TokenResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetConnectionsConnectionIDTokenResponse parses an HTTP response from a GetConnectionsConnectionIDTokenWithResponse call
func ParseGetConnectionsConnectionIDTokenResponse(rsp *http.Response) (*GetConnectionsConnectionIDTokenResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetConnectionsConnectionIDTokenResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest TokenResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetHealthResponse parses an HTTP response from a GetHealthWithResponse call
func ParseGetHealthResponse(rsp *http.Response) (*GetHealthResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetHealthResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseGetProvidersResponse parses an HTTP response from a GetProvidersWithResponse call
func ParseGetProvidersResponse(rsp *http.Response) (*GetProvidersResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetProvidersResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []struct {
			Id   *string `json:"id,omitempty"`
			Name *string `json:"name,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostProvidersResponse parses an HTTP response from a PostProvidersWithResponse call
func ParsePostProvidersResponse(rsp *http.Response) (*PostProvidersResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostProvidersResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest struct {
			Id      *string `json:"id,omitempty"`
			Message *string `json:"message,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	}

	return response, nil
}

// ParseGetProvidersByNameNameResponse parses an HTTP response from a GetProvidersByNameNameWithResponse call
func ParseGetProvidersByNameNameResponse(rsp *http.Response) (*GetProvidersByNameNameResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetProvidersByNameNameResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			Id *string `json:"id,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetProvidersMetadataResponse parses an HTTP response from a GetProvidersMetadataWithResponse call
func ParseGetProvidersMetadataResponse(rsp *http.Response) (*GetProvidersMetadataResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetProvidersMetadataResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest MetadataResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseDeleteProvidersIdResponse parses an HTTP response from a DeleteProvidersIdWithResponse call
func ParseDeleteProvidersIdResponse(rsp *http.Response) (*DeleteProvidersIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteProvidersIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseGetProvidersIdResponse parses an HTTP response from a GetProvidersIdWithResponse call
func ParseGetProvidersIdResponse(rsp *http.Response) (*GetProvidersIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetProvidersIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ProviderProfile
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePutProvidersIdResponse parses an HTTP response from a PutProvidersIdWithResponse call
func ParsePutProvidersIdResponse(rsp *http.Response) (*PutProvidersIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PutProvidersIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}
